package com.tompy.directive;

/**
 * There are many types of events, each represented in a list here.
 */
public enum EventType {
    EVENT_AREA_SEARCH, EVENT_AREA_NORTH_SEARCH, EVENT_AREA_EAST_SEARCH, EVENT_AREA_SOUTH_SEARCH, EVENT_AREA_WEST_SEARCH,
    EVENT_AREA_ENTER, EVENT_AREA_ENTER_NORTH, EVENT_AREA_ENTER_EAST, EVENT_AREA_ENTER_SOUTH, EVENT_AREA_ENTER_WEST,
    EVENT_AREA_EXIT, EVENT_AREA_EXIT_NORTH, EVENT_AREA_EXIT_EAST, EVENT_AREA_EXIT_SOUTH, EVENT_AREA_EXIT_WEST,
    EVENT_INTERACTION, EVENT_FEATURE_SEARCH, EVENT_FEATURE_OPEN, EVENT_FEATURE_CLOSE, EVENT_FEATURE_LOCK,
    EVENT_FEATURE_UNLOCK, EVENT_FEATURE_DRINK, EVENT_FEATURE_TRAP, EVENT_EXPLORING, EVENT_WEAPON_BEFORE_ATTACK,
    EVENT_WEAPON_AFTER_ATTACK, EVENT_WEAPON_ATTACK_SUCCESS, EVENT_WEAPON_ATTACK_FAILURE, EVENT_FEATURE_OPEN_BUT_LOCKED,
    EVENT_FEATURE_UNABLE_TO_LOCK, EVENT_FEATURE_UNABLE_TO_UNLOCK, EVENT_KEY_BEFORE_USE, EVENT_KEY_AFTER_USE,
    EVENT_KEY_LOCK, EVENT_KEY_UNLOCK, EVENT_BEFORE_POTION, EVENT_AFTER_POTION, EVENT_AREA_PRE_FEATURE_SEARCH,
    EVENT_AREA_PRE_ITEM_SEARCH, EVENT_ITEM_MISHANDLE_FEATURE, EVENT_FEATURE_MISHANDLE_ITEM, EVENT_ENCOUNTER_END,
    EVENT_ENCOUNTER_START, EVENT_EXPLORE_START, EVENT_EXPLORE_END, EVENT_AREA_PRE_FEATURE_DIRECTION_SEARCH,
    EVENT_ITEM_MISUSE, EVENT_FEATURE_MISUSE, EVENT_ACTOR_PROGRAM
}
